### ISSUE TITLE
Prototype simple end-to-end example

### ISSUE THREAD

**Issue by oubiwann** [lfex/try.lfe.io#2]
Let's get something working locally, just enough to pass data from one component to the next. Components:

* A container
* A REST server (written in LFE)
* A JS client
* An `mdbook` with example LFE code on one of its pages

Feature-level work for proof-of-concept:
* [ ] #10 - a deployment approach and proof of concept (e.g., a container that could be deployed to AWS using ECS)
* [ ] #21 - a service, protocol, and proof of concept that could be used across *.lfe.io and from JS (e.g., REST & HTTP)
* [ ] #22 - update existing try-lfe JS to make sure we're moving in a good/supportable direction
* [ ] #20 - some JS hacking in mdbook's book.js to make sure we can properly render results from the REST service

We should be able to prove out a full set of round trips locally using Docker ... might have to do some hacking / tweaking for local CORS or cross-site scripting?
