### ISSUE TITLE
Deployable Proof of Concept

### ISSUE THREAD

**Issue by oubiwann** [lfex/try.lfe.io#23]
Features/Tasks:

* #12 - Create Dockerfile for use on the LFE domain
* [ ] Choose a deployment platform (e.g., AWS)
* [ ] Deploy (but only for short durations)
* [ ] Test like crazy
* [ ] Iterate until stable
