### ISSUE TITLE
Prepare for secure deployment

### ISSUE THREAD

**Issue by oubiwann** [lfex/try.lfe.io#24]
Features/tasks:

* [ ] #9 - Handle LFE bytes in REST handler
* [ ] #4 - No unsafe functions
* [ ] #8 - Support session management
* [ ] #14 - Implement per-session environments
